/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_point_x: (a: number) => number;
export const __wbg_get_point_y: (a: number) => number;
export const __wbg_point_free: (a: number, b: number) => void;
export const __wbg_puzzleengine_free: (a: number, b: number) => void;
export const __wbg_set_point_x: (a: number, b: number) => void;
export const __wbg_set_point_y: (a: number, b: number) => void;
export const main_js: () => void;
export const point_distance: (a: number, b: number) => number;
export const point_new: (a: number, b: number) => number;
export const point_translate: (a: number, b: number, c: number) => number;
export const puzzleengine_deselect_piece: (a: number) => void;
export const puzzleengine_drag_move: (a: number, b: number, c: number, d: number, e: number) => number;
export const puzzleengine_drag_offset: (a: number, b: number, c: number, d: number, e: number) => number;
export const puzzleengine_get_cassini_info: (a: number) => [number, number];
export const puzzleengine_get_mathematical_explanation: (a: number) => [number, number];
export const puzzleengine_get_piece_positions_json: (a: number) => [number, number];
export const puzzleengine_get_selected_piece: (a: number) => [number, number];
export const puzzleengine_get_status_message: (a: number) => [number, number];
export const puzzleengine_is_laser_visible: (a: number) => number;
export const puzzleengine_is_lozenge_visible: (a: number) => number;
export const puzzleengine_is_magnify_bend: (a: number) => number;
export const puzzleengine_new: () => number;
export const puzzleengine_render_svg: (a: number) => [number, number];
export const puzzleengine_render_svg_with_options: (a: number, b: number, c: number, d: number) => [number, number];
export const puzzleengine_reset: (a: number) => void;
export const puzzleengine_run_validation: (a: number) => [number, number];
export const puzzleengine_select_piece: (a: number, b: number, c: number) => number;
export const puzzleengine_set_configuration: (a: number, b: number, c: number) => number;
export const puzzleengine_set_configuration_type: (a: number, b: number) => number;
export const puzzleengine_set_laser_visible: (a: number, b: number) => void;
export const puzzleengine_set_lozenge_visible: (a: number, b: number) => void;
export const puzzleengine_set_magnify_bend: (a: number, b: number) => void;
export const puzzleengine_set_piece_position: (a: number, b: number, c: number, d: number, e: number) => number;
export const puzzleengine_snap_all_pieces: (a: number) => void;
export const puzzleengine_snap_selected_piece: (a: number, b: number, c: number) => number;
export const puzzleengine_toggle_laser: (a: number) => number;
export const puzzleengine_toggle_lozenge: (a: number) => number;
export const puzzleengine_toggle_magnification: (a: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
